"""empty message

Revision ID: 785dde2eb39a
Revises: 4502eba1debb
Create Date: 2018-11-12 16:08:54.896800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '785dde2eb39a'
down_revision = '4502eba1debb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_sqlalchemy_user', 'account',
               existing_type=mysql.VARCHAR(length=56),
               nullable=False)
    op.create_unique_constraint(None, 'tbl_sqlalchemy_user', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_sqlalchemy_user', type_='unique')
    op.alter_column('tbl_sqlalchemy_user', 'account',
               existing_type=mysql.VARCHAR(length=56),
               nullable=True)
    # ### end Alembic commands ###
