"""empty message

Revision ID: f7fe27427309
Revises: 4c093f02e763
Create Date: 2018-11-08 21:51:30.122589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fe27427309'
down_revision = '4c093f02e763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_user_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['tbl_sqlalchemy_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_sqlalchemy_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_user_association')
    # ### end Alembic commands ###
